workflows:
  ios-workflow:
    name: Longmidle iOS
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: 3.35.7
      xcode: latest

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build iOS
        script: flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa